version: "3.7"

networks:
  frontend:
    external: true
    name: wai_frontend
  backend:
    external: true
    name: wai_backend

services:
  express:
    image: wai-express-api:dev
    build:
      context: .
    ports:
      - "${PORT_PROD}:${PORT_PROD}"
    networks:
      - frontend
      - backend
