version: '3.7'

networks:
  cache:
    driver: bridge

volumes:
  pg_data:

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - cache
    volumes:
    - pg_data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:2.2.0
    depends_on:
      - postgres
    command: kong migrations bootstrap --vv
    environment:
      - KONG_DATABASE= ${POSTGRES_DATABASE_TYPE}
      - KONG_PG_DATABASE= ${POSTGRES_DATABASE}
      - KONG_PG_USER= ${POSTGRES_USER}      
      - KONG_PG_PASSWORD= ${POSTGRES_PASSWORD}      
      - KONG_PG_HOST= postgres
      - KONG_LOG_LEVEL= info
      - KONG_PROXY_ACCESS_LOG= /dev/stdout
      - KONG_ADMIN_ACCESS_LOG= /dev/stdout
      - KONG_PROXY_ERROR_LOG= /dev/stderr
      - KONG_ADMIN_ERROR_LOG= /dev/stderr
      - KONG_ADMIN_LISTEN= 0.0.0.0:8001,0.0.0.0:8444 ssl
    networks:
      - cache

  kong:
    image: kong:2.2.0
    depends_on:
      - postgres
    environment:
      - KONG_DATABASE= ${POSTGRES_DATABASE_TYPE}
      - KONG_PG_DATABASE= ${POSTGRES_DATABASE}
      - KONG_PG_USER= ${POSTGRES_USER}      
      - KONG_PG_PASSWORD= ${POSTGRES_PASSWORD}      
      - KONG_PG_HOST= postgres
      - KONG_LOG_LEVEL= info
      - KONG_PROXY_ACCESS_LOG= /dev/stdout
      - KONG_ADMIN_ACCESS_LOG= /dev/stdout
      - KONG_PROXY_ERROR_LOG= /dev/stderr
      - KONG_ADMIN_ERROR_LOG= /dev/stderr
      - KONG_ADMIN_LISTEN= 0.0.0.0:8001,0.0.0.0:8444 ssl
      - KONG_CUSTOM_PLUGINS=rate-limiting,jwt-signer,jwt
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - cache

  petstore:
    image: swaggerapi/petstore
    networks:
      - cache
