version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@1.1.2

jobs:
  build_and_test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - codecov/upload:
          file: coverage/clover.xml

workflows:
  build_and_test: 
    jobs:
      - build_and_test

