# Matomo allowed modules and methods
# To force a recompile of the yaml in dev mode edit the comment in config.js

enabled:
  api:
    # Actions.get: R
    # Actions.getPageUrls: R
    # Actions.getPageUrlsFollowingSiteSearch: R
    # Actions.getPageTitlesFollowingSiteSearch: R
    # Actions.getEntryPageUrls: R
    # Actions.getExitPageUrls: R
    # Actions.getPageUrl: R
    # Actions.getPageTitles: R
    # Actions.getEntryPageTitles: R
    # Actions.getExitPageTitles: R
    # Actions.getPageTitle: R
    # Actions.getDownloads: R
    # Actions.getDownload: R
    # Actions.getOutlinks: R
    # Actions.getOutlink: R
    # Actions.getSiteSearchKeywords: R
    # Actions.getSiteSearchNoResultKeywords: R
    # Actions.getSiteSearchCategories: R
    # CustomDimensions.getCustomDimension: R
    # CustomDimensions.configureNewCustomDimension: RW
    # CustomDimensions.configureExistingCustomDimension: RW
    # CustomDimensions.getConfiguredCustomDimensions: R
    # CustomDimensions.getConfiguredCustomDimensionsHavingScope: R
    # CustomDimensions.getAvailableScopes: R
    # CustomDimensions.getAvailableExtractionDimensions: R
    # DevicesDetection.getType: R
    # DevicesDetection.getBrand: R
    # DevicesDetection.getModel: R
    # DevicesDetection.getOsFamilies: R
    # DevicesDetection.getOsVersions: R
    # DevicesDetection.getBrowsers: R
    # DevicesDetection.getBrowserVersions: R
    # DevicesDetection.getBrowserEngines: R
    # Events.getCategory: R
    # Events.getAction: R
    # Events.getName: R
    # Events.getActionFromCategoryId: R
    # Events.getNameFromCategoryId: R
    # Events.getCategoryFromActionId: R
    # Events.getNameFromActionId: R
    # Events.getActionFromNameId: R
    # Events.getCategoryFromNameId: R
    # Goals.getGoal: R
    # Goals.getGoals: R
    # Goals.addGoal: RW
    # Goals.updateGoal: RW
    # Goals.deleteGoal: RW
    # Goals.get: R
    # Goals.getDaysToConversion: R
    # Goals.getVisitsUntilConversion: R
    # Referrers.get: R
    # Referrers.getReferrerType: R
    # Referrers.getAll: R
    # Referrers.getKeywords: R
    # Referrers.getSearchEnginesFromKeywordId: R
    # Referrers.getSearchEngines: R
    # Referrers.getKeywordsFromSearchEngineId: R
    # Referrers.getCampaigns: R
    # Referrers.getKeywordsFromCampaignId: R
    # Referrers.getWebsites: R
    # Referrers.getUrlsFromWebsiteId: R
    # Referrers.getSocials: R
    # Referrers.getUrlsForSocial: R
    # Referrers.getNumberOfDistinctSearchEngines: R
    # Referrers.getNumberOfDistinctSocialNetworks: R
    # Referrers.getNumberOfDistinctKeywords: R
    # Referrers.getNumberOfDistinctCampaigns: R
    # Referrers.getNumberOfDistinctWebsites: R
    # Referrers.getNumberOfDistinctWebsitesUrls: R
    # Resolution.getResolution: R
    # Resolution.getConfiguration: R
    # UserCountry.getCountry: R
    # UserCountry.getContinent: R
    # UserCountry.getRegion: R
    # UserCountry.getCity: R
    # UserCountry.getCountryCodeMapping: R
    # UserCountry.getLocationFromIP: R
    # UserCountry.setLocationProvider: R
    # UserCountry.getNumberOfDistinctCountries: R
    # VisitTime.getVisitInformationPerLocalTime: R
    # VisitTime.getVisitInformationPerServerTime: R
    # VisitTime.getByDayOfWeek: R
    # VisitorInterest.getNumberOfVisitsPerVisitDuration: R
    # VisitorInterest.getNumberOfVisitsPerPage: R
    # VisitorInterest.getNumberOfVisitsByDaysSinceLast: R
    # VisitorInterest.getNumberOfVisitsByVisitCount: R
    VisitsSummary.get: R
    # VisitsSummary.getVisits: R
    # VisitsSummary.getUniqueVisitors: R
    # VisitsSummary.getUsers: R
    # VisitsSummary.getActions: R
    # VisitsSummary.getMaxActions: R
    # VisitsSummary.getBounceCount: R
    # VisitsSummary.getVisitsConverted: R
    # VisitsSummary.getSumVisitsLength: R
    # VisitsSummary.getSumVisitsLengthPretty: R
# API that won't require authorization (comment out to disable)
public:
  api:
    # API.getBulkRequest: true
