# Matomo allowed modules and methods
# To force a recompile of the yaml in dev mode edit the comment in config.js

enabled:
  api:
    API.getBulkRequest: R
    API.getMatomoVersion: R
    SitesManager.getSiteUrlsFromId: RW
    API.getWidgetMetadata: R
  # For testing purposes only
  test:
    API.test: RW
    API.testWrite: RW
# API that won't require authorization (comment out to disable)
public:
  api:
    - API.getBulkRequest
