# Matomo allowed modules and methods
# To force a recompile of the yaml in dev mode edit the comment in config.js

enabledModules:
  module:
    - name: api
      methods:
        - API.getBulkRequest|R
        - API.getMatomoVersion|W
        - SitesManager.getSiteUrlsFromId|W
        - API.getWidgetMetadata|R
    #For testing purposes only
    - name: test
      methods:
        - API.test|W
        - API.testWrite|W
publicMethods:
  - API.getBulkRequest
