# Create local templates
- hosts: localhost
  gather_facts: no
  tasks:
    - name: K8S .:. Compile templates locally
      vars:
        wai_k8s_deployment_dir: "{{ playbook_dir }}/compiled-templates/k8s"
      tags:
        - never
        - templates
      import_tasks: k8s-templates.yml

# Deploy K8S WAI Resources
- hosts: kube-master[0]
  tasks:

    - name: K8S .:. Compile resources templates
      include_tasks: k8s-templates.yml

    - name: K8S .:. Enumerate deployment files
      shell: 'find {{ wai_k8s_deployment_dir }} -type f | sort'
      register: deployment_files

    - name: K8S .:. Deploy Web Analytics Italia - WAI API changes
      kube:
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ item }}"
        state: "latest"
      with_items: "{{ deployment_files.stdout_lines }}"
